### ISSUE TITLE
I can't install python-lzf,need ur help

### ISSUE THREAD

**Issue by celery-xqq** [teepark/python-lzf#6]
I can't install python-lzf:
input : pip install python-lzf
I get this error:
lzf_module.c:3:20: fatal error: Python.h: No such file or directory
     #include "Python.h"
                        ^
    compilation terminated.
    error: command 'gcc' failed with exit status 1

**Comment by smartwhistler** [comment]
install gcc, i have told you, haha

**Comment by lizhiyou88** [comment]
yum -y install python-devel
